// Autogenerated. Do not modify!
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(AuthService, NSObject)

RCT_EXTERN_METHOD(signIn:(NSDictionary *)jsReq resolve:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject)

@end
