// Autogenerated. Do not modify!
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(ToursService, NSObject)

RCT_EXTERN_METHOD(getTours:(NSDictionary *)jsReq resolve:(RCTPromiseResolveBlock)resolve reject:(RCTPromiseRejectBlock)reject)

@end
