# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  # use_modular_headers!

  # Pods for mpost
  pod 'SwiftGRPC', :git => 'https://github.com/trackforce/grpc-swift', :tag => '0.5.0'

end
