// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: debug.proto

package debug;

public final class DebugOuterClass {
  private DebugOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetDebugDataRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:debug.GetDebugDataRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string guardroomId = 1;</code>
     */
    java.lang.String getGuardroomId();
    /**
     * <code>string guardroomId = 1;</code>
     */
    com.google.protobuf.ByteString
        getGuardroomIdBytes();
  }
  /**
   * Protobuf type {@code debug.GetDebugDataRequest}
   */
  public  static final class GetDebugDataRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:debug.GetDebugDataRequest)
      GetDebugDataRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetDebugDataRequest.newBuilder() to construct.
    private GetDebugDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetDebugDataRequest() {
      guardroomId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetDebugDataRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              guardroomId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return debug.DebugOuterClass.internal_static_debug_GetDebugDataRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return debug.DebugOuterClass.internal_static_debug_GetDebugDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              debug.DebugOuterClass.GetDebugDataRequest.class, debug.DebugOuterClass.GetDebugDataRequest.Builder.class);
    }

    public static final int GUARDROOMID_FIELD_NUMBER = 1;
    private volatile java.lang.Object guardroomId_;
    /**
     * <code>string guardroomId = 1;</code>
     */
    public java.lang.String getGuardroomId() {
      java.lang.Object ref = guardroomId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        guardroomId_ = s;
        return s;
      }
    }
    /**
     * <code>string guardroomId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGuardroomIdBytes() {
      java.lang.Object ref = guardroomId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        guardroomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGuardroomIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, guardroomId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGuardroomIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, guardroomId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof debug.DebugOuterClass.GetDebugDataRequest)) {
        return super.equals(obj);
      }
      debug.DebugOuterClass.GetDebugDataRequest other = (debug.DebugOuterClass.GetDebugDataRequest) obj;

      boolean result = true;
      result = result && getGuardroomId()
          .equals(other.getGuardroomId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GUARDROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getGuardroomId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static debug.DebugOuterClass.GetDebugDataRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static debug.DebugOuterClass.GetDebugDataRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static debug.DebugOuterClass.GetDebugDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static debug.DebugOuterClass.GetDebugDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static debug.DebugOuterClass.GetDebugDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static debug.DebugOuterClass.GetDebugDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static debug.DebugOuterClass.GetDebugDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static debug.DebugOuterClass.GetDebugDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static debug.DebugOuterClass.GetDebugDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static debug.DebugOuterClass.GetDebugDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static debug.DebugOuterClass.GetDebugDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static debug.DebugOuterClass.GetDebugDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(debug.DebugOuterClass.GetDebugDataRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code debug.GetDebugDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:debug.GetDebugDataRequest)
        debug.DebugOuterClass.GetDebugDataRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return debug.DebugOuterClass.internal_static_debug_GetDebugDataRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return debug.DebugOuterClass.internal_static_debug_GetDebugDataRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                debug.DebugOuterClass.GetDebugDataRequest.class, debug.DebugOuterClass.GetDebugDataRequest.Builder.class);
      }

      // Construct using debug.DebugOuterClass.GetDebugDataRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        guardroomId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return debug.DebugOuterClass.internal_static_debug_GetDebugDataRequest_descriptor;
      }

      public debug.DebugOuterClass.GetDebugDataRequest getDefaultInstanceForType() {
        return debug.DebugOuterClass.GetDebugDataRequest.getDefaultInstance();
      }

      public debug.DebugOuterClass.GetDebugDataRequest build() {
        debug.DebugOuterClass.GetDebugDataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public debug.DebugOuterClass.GetDebugDataRequest buildPartial() {
        debug.DebugOuterClass.GetDebugDataRequest result = new debug.DebugOuterClass.GetDebugDataRequest(this);
        result.guardroomId_ = guardroomId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof debug.DebugOuterClass.GetDebugDataRequest) {
          return mergeFrom((debug.DebugOuterClass.GetDebugDataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(debug.DebugOuterClass.GetDebugDataRequest other) {
        if (other == debug.DebugOuterClass.GetDebugDataRequest.getDefaultInstance()) return this;
        if (!other.getGuardroomId().isEmpty()) {
          guardroomId_ = other.guardroomId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        debug.DebugOuterClass.GetDebugDataRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (debug.DebugOuterClass.GetDebugDataRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object guardroomId_ = "";
      /**
       * <code>string guardroomId = 1;</code>
       */
      public java.lang.String getGuardroomId() {
        java.lang.Object ref = guardroomId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          guardroomId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string guardroomId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGuardroomIdBytes() {
        java.lang.Object ref = guardroomId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          guardroomId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string guardroomId = 1;</code>
       */
      public Builder setGuardroomId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        guardroomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string guardroomId = 1;</code>
       */
      public Builder clearGuardroomId() {
        
        guardroomId_ = getDefaultInstance().getGuardroomId();
        onChanged();
        return this;
      }
      /**
       * <code>string guardroomId = 1;</code>
       */
      public Builder setGuardroomIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        guardroomId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:debug.GetDebugDataRequest)
    }

    // @@protoc_insertion_point(class_scope:debug.GetDebugDataRequest)
    private static final debug.DebugOuterClass.GetDebugDataRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new debug.DebugOuterClass.GetDebugDataRequest();
    }

    public static debug.DebugOuterClass.GetDebugDataRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetDebugDataRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetDebugDataRequest>() {
      public GetDebugDataRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetDebugDataRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetDebugDataRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetDebugDataRequest> getParserForType() {
      return PARSER;
    }

    public debug.DebugOuterClass.GetDebugDataRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetDebugDataReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:debug.GetDebugDataReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .debug.Tour items = 1;</code>
     */
    java.util.List<debug.DebugOuterClass.Tour> 
        getItemsList();
    /**
     * <code>repeated .debug.Tour items = 1;</code>
     */
    debug.DebugOuterClass.Tour getItems(int index);
    /**
     * <code>repeated .debug.Tour items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .debug.Tour items = 1;</code>
     */
    java.util.List<? extends debug.DebugOuterClass.TourOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .debug.Tour items = 1;</code>
     */
    debug.DebugOuterClass.TourOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code debug.GetDebugDataReply}
   */
  public  static final class GetDebugDataReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:debug.GetDebugDataReply)
      GetDebugDataReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetDebugDataReply.newBuilder() to construct.
    private GetDebugDataReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetDebugDataReply() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetDebugDataReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<debug.DebugOuterClass.Tour>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(debug.DebugOuterClass.Tour.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return debug.DebugOuterClass.internal_static_debug_GetDebugDataReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return debug.DebugOuterClass.internal_static_debug_GetDebugDataReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              debug.DebugOuterClass.GetDebugDataReply.class, debug.DebugOuterClass.GetDebugDataReply.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<debug.DebugOuterClass.Tour> items_;
    /**
     * <code>repeated .debug.Tour items = 1;</code>
     */
    public java.util.List<debug.DebugOuterClass.Tour> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .debug.Tour items = 1;</code>
     */
    public java.util.List<? extends debug.DebugOuterClass.TourOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .debug.Tour items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .debug.Tour items = 1;</code>
     */
    public debug.DebugOuterClass.Tour getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .debug.Tour items = 1;</code>
     */
    public debug.DebugOuterClass.TourOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof debug.DebugOuterClass.GetDebugDataReply)) {
        return super.equals(obj);
      }
      debug.DebugOuterClass.GetDebugDataReply other = (debug.DebugOuterClass.GetDebugDataReply) obj;

      boolean result = true;
      result = result && getItemsList()
          .equals(other.getItemsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static debug.DebugOuterClass.GetDebugDataReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static debug.DebugOuterClass.GetDebugDataReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static debug.DebugOuterClass.GetDebugDataReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static debug.DebugOuterClass.GetDebugDataReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static debug.DebugOuterClass.GetDebugDataReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static debug.DebugOuterClass.GetDebugDataReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static debug.DebugOuterClass.GetDebugDataReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static debug.DebugOuterClass.GetDebugDataReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static debug.DebugOuterClass.GetDebugDataReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static debug.DebugOuterClass.GetDebugDataReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static debug.DebugOuterClass.GetDebugDataReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static debug.DebugOuterClass.GetDebugDataReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(debug.DebugOuterClass.GetDebugDataReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code debug.GetDebugDataReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:debug.GetDebugDataReply)
        debug.DebugOuterClass.GetDebugDataReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return debug.DebugOuterClass.internal_static_debug_GetDebugDataReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return debug.DebugOuterClass.internal_static_debug_GetDebugDataReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                debug.DebugOuterClass.GetDebugDataReply.class, debug.DebugOuterClass.GetDebugDataReply.Builder.class);
      }

      // Construct using debug.DebugOuterClass.GetDebugDataReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return debug.DebugOuterClass.internal_static_debug_GetDebugDataReply_descriptor;
      }

      public debug.DebugOuterClass.GetDebugDataReply getDefaultInstanceForType() {
        return debug.DebugOuterClass.GetDebugDataReply.getDefaultInstance();
      }

      public debug.DebugOuterClass.GetDebugDataReply build() {
        debug.DebugOuterClass.GetDebugDataReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public debug.DebugOuterClass.GetDebugDataReply buildPartial() {
        debug.DebugOuterClass.GetDebugDataReply result = new debug.DebugOuterClass.GetDebugDataReply(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof debug.DebugOuterClass.GetDebugDataReply) {
          return mergeFrom((debug.DebugOuterClass.GetDebugDataReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(debug.DebugOuterClass.GetDebugDataReply other) {
        if (other == debug.DebugOuterClass.GetDebugDataReply.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        debug.DebugOuterClass.GetDebugDataReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (debug.DebugOuterClass.GetDebugDataReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<debug.DebugOuterClass.Tour> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<debug.DebugOuterClass.Tour>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          debug.DebugOuterClass.Tour, debug.DebugOuterClass.Tour.Builder, debug.DebugOuterClass.TourOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public java.util.List<debug.DebugOuterClass.Tour> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public debug.DebugOuterClass.Tour getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public Builder setItems(
          int index, debug.DebugOuterClass.Tour value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public Builder setItems(
          int index, debug.DebugOuterClass.Tour.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public Builder addItems(debug.DebugOuterClass.Tour value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public Builder addItems(
          int index, debug.DebugOuterClass.Tour value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public Builder addItems(
          debug.DebugOuterClass.Tour.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public Builder addItems(
          int index, debug.DebugOuterClass.Tour.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends debug.DebugOuterClass.Tour> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public debug.DebugOuterClass.Tour.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public debug.DebugOuterClass.TourOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public java.util.List<? extends debug.DebugOuterClass.TourOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public debug.DebugOuterClass.Tour.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            debug.DebugOuterClass.Tour.getDefaultInstance());
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public debug.DebugOuterClass.Tour.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, debug.DebugOuterClass.Tour.getDefaultInstance());
      }
      /**
       * <code>repeated .debug.Tour items = 1;</code>
       */
      public java.util.List<debug.DebugOuterClass.Tour.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          debug.DebugOuterClass.Tour, debug.DebugOuterClass.Tour.Builder, debug.DebugOuterClass.TourOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              debug.DebugOuterClass.Tour, debug.DebugOuterClass.Tour.Builder, debug.DebugOuterClass.TourOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:debug.GetDebugDataReply)
    }

    // @@protoc_insertion_point(class_scope:debug.GetDebugDataReply)
    private static final debug.DebugOuterClass.GetDebugDataReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new debug.DebugOuterClass.GetDebugDataReply();
    }

    public static debug.DebugOuterClass.GetDebugDataReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetDebugDataReply>
        PARSER = new com.google.protobuf.AbstractParser<GetDebugDataReply>() {
      public GetDebugDataReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetDebugDataReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetDebugDataReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetDebugDataReply> getParserForType() {
      return PARSER;
    }

    public debug.DebugOuterClass.GetDebugDataReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TourOrBuilder extends
      // @@protoc_insertion_point(interface_extends:debug.Tour)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string courseType = 3;</code>
     */
    java.lang.String getCourseType();
    /**
     * <code>string courseType = 3;</code>
     */
    com.google.protobuf.ByteString
        getCourseTypeBytes();

    /**
     * <code>string duration = 4;</code>
     */
    java.lang.String getDuration();
    /**
     * <code>string duration = 4;</code>
     */
    com.google.protobuf.ByteString
        getDurationBytes();

    /**
     * <code>string stripName = 5;</code>
     */
    java.lang.String getStripName();
    /**
     * <code>string stripName = 5;</code>
     */
    com.google.protobuf.ByteString
        getStripNameBytes();

    /**
     * <code>bool isActive = 6;</code>
     */
    boolean getIsActive();
  }
  /**
   * Protobuf type {@code debug.Tour}
   */
  public  static final class Tour extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:debug.Tour)
      TourOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tour.newBuilder() to construct.
    private Tour(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tour() {
      id_ = "";
      name_ = "";
      courseType_ = "";
      duration_ = "";
      stripName_ = "";
      isActive_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tour(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              courseType_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              duration_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              stripName_ = s;
              break;
            }
            case 48: {

              isActive_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return debug.DebugOuterClass.internal_static_debug_Tour_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return debug.DebugOuterClass.internal_static_debug_Tour_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              debug.DebugOuterClass.Tour.class, debug.DebugOuterClass.Tour.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COURSETYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object courseType_;
    /**
     * <code>string courseType = 3;</code>
     */
    public java.lang.String getCourseType() {
      java.lang.Object ref = courseType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        courseType_ = s;
        return s;
      }
    }
    /**
     * <code>string courseType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCourseTypeBytes() {
      java.lang.Object ref = courseType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        courseType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DURATION_FIELD_NUMBER = 4;
    private volatile java.lang.Object duration_;
    /**
     * <code>string duration = 4;</code>
     */
    public java.lang.String getDuration() {
      java.lang.Object ref = duration_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        duration_ = s;
        return s;
      }
    }
    /**
     * <code>string duration = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDurationBytes() {
      java.lang.Object ref = duration_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        duration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRIPNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object stripName_;
    /**
     * <code>string stripName = 5;</code>
     */
    public java.lang.String getStripName() {
      java.lang.Object ref = stripName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stripName_ = s;
        return s;
      }
    }
    /**
     * <code>string stripName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStripNameBytes() {
      java.lang.Object ref = stripName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stripName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISACTIVE_FIELD_NUMBER = 6;
    private boolean isActive_;
    /**
     * <code>bool isActive = 6;</code>
     */
    public boolean getIsActive() {
      return isActive_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getCourseTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, courseType_);
      }
      if (!getDurationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, duration_);
      }
      if (!getStripNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, stripName_);
      }
      if (isActive_ != false) {
        output.writeBool(6, isActive_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getCourseTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, courseType_);
      }
      if (!getDurationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, duration_);
      }
      if (!getStripNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, stripName_);
      }
      if (isActive_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isActive_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof debug.DebugOuterClass.Tour)) {
        return super.equals(obj);
      }
      debug.DebugOuterClass.Tour other = (debug.DebugOuterClass.Tour) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getCourseType()
          .equals(other.getCourseType());
      result = result && getDuration()
          .equals(other.getDuration());
      result = result && getStripName()
          .equals(other.getStripName());
      result = result && (getIsActive()
          == other.getIsActive());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + COURSETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCourseType().hashCode();
      hash = (37 * hash) + DURATION_FIELD_NUMBER;
      hash = (53 * hash) + getDuration().hashCode();
      hash = (37 * hash) + STRIPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getStripName().hashCode();
      hash = (37 * hash) + ISACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsActive());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static debug.DebugOuterClass.Tour parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static debug.DebugOuterClass.Tour parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static debug.DebugOuterClass.Tour parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static debug.DebugOuterClass.Tour parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static debug.DebugOuterClass.Tour parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static debug.DebugOuterClass.Tour parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static debug.DebugOuterClass.Tour parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static debug.DebugOuterClass.Tour parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static debug.DebugOuterClass.Tour parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static debug.DebugOuterClass.Tour parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static debug.DebugOuterClass.Tour parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static debug.DebugOuterClass.Tour parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(debug.DebugOuterClass.Tour prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code debug.Tour}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:debug.Tour)
        debug.DebugOuterClass.TourOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return debug.DebugOuterClass.internal_static_debug_Tour_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return debug.DebugOuterClass.internal_static_debug_Tour_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                debug.DebugOuterClass.Tour.class, debug.DebugOuterClass.Tour.Builder.class);
      }

      // Construct using debug.DebugOuterClass.Tour.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        courseType_ = "";

        duration_ = "";

        stripName_ = "";

        isActive_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return debug.DebugOuterClass.internal_static_debug_Tour_descriptor;
      }

      public debug.DebugOuterClass.Tour getDefaultInstanceForType() {
        return debug.DebugOuterClass.Tour.getDefaultInstance();
      }

      public debug.DebugOuterClass.Tour build() {
        debug.DebugOuterClass.Tour result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public debug.DebugOuterClass.Tour buildPartial() {
        debug.DebugOuterClass.Tour result = new debug.DebugOuterClass.Tour(this);
        result.id_ = id_;
        result.name_ = name_;
        result.courseType_ = courseType_;
        result.duration_ = duration_;
        result.stripName_ = stripName_;
        result.isActive_ = isActive_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof debug.DebugOuterClass.Tour) {
          return mergeFrom((debug.DebugOuterClass.Tour)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(debug.DebugOuterClass.Tour other) {
        if (other == debug.DebugOuterClass.Tour.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getCourseType().isEmpty()) {
          courseType_ = other.courseType_;
          onChanged();
        }
        if (!other.getDuration().isEmpty()) {
          duration_ = other.duration_;
          onChanged();
        }
        if (!other.getStripName().isEmpty()) {
          stripName_ = other.stripName_;
          onChanged();
        }
        if (other.getIsActive() != false) {
          setIsActive(other.getIsActive());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        debug.DebugOuterClass.Tour parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (debug.DebugOuterClass.Tour) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object courseType_ = "";
      /**
       * <code>string courseType = 3;</code>
       */
      public java.lang.String getCourseType() {
        java.lang.Object ref = courseType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          courseType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string courseType = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCourseTypeBytes() {
        java.lang.Object ref = courseType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          courseType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string courseType = 3;</code>
       */
      public Builder setCourseType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        courseType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string courseType = 3;</code>
       */
      public Builder clearCourseType() {
        
        courseType_ = getDefaultInstance().getCourseType();
        onChanged();
        return this;
      }
      /**
       * <code>string courseType = 3;</code>
       */
      public Builder setCourseTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        courseType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object duration_ = "";
      /**
       * <code>string duration = 4;</code>
       */
      public java.lang.String getDuration() {
        java.lang.Object ref = duration_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          duration_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string duration = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDurationBytes() {
        java.lang.Object ref = duration_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          duration_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string duration = 4;</code>
       */
      public Builder setDuration(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string duration = 4;</code>
       */
      public Builder clearDuration() {
        
        duration_ = getDefaultInstance().getDuration();
        onChanged();
        return this;
      }
      /**
       * <code>string duration = 4;</code>
       */
      public Builder setDurationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        duration_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stripName_ = "";
      /**
       * <code>string stripName = 5;</code>
       */
      public java.lang.String getStripName() {
        java.lang.Object ref = stripName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stripName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stripName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStripNameBytes() {
        java.lang.Object ref = stripName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stripName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stripName = 5;</code>
       */
      public Builder setStripName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stripName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stripName = 5;</code>
       */
      public Builder clearStripName() {
        
        stripName_ = getDefaultInstance().getStripName();
        onChanged();
        return this;
      }
      /**
       * <code>string stripName = 5;</code>
       */
      public Builder setStripNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stripName_ = value;
        onChanged();
        return this;
      }

      private boolean isActive_ ;
      /**
       * <code>bool isActive = 6;</code>
       */
      public boolean getIsActive() {
        return isActive_;
      }
      /**
       * <code>bool isActive = 6;</code>
       */
      public Builder setIsActive(boolean value) {
        
        isActive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isActive = 6;</code>
       */
      public Builder clearIsActive() {
        
        isActive_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:debug.Tour)
    }

    // @@protoc_insertion_point(class_scope:debug.Tour)
    private static final debug.DebugOuterClass.Tour DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new debug.DebugOuterClass.Tour();
    }

    public static debug.DebugOuterClass.Tour getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tour>
        PARSER = new com.google.protobuf.AbstractParser<Tour>() {
      public Tour parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tour(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tour> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tour> getParserForType() {
      return PARSER;
    }

    public debug.DebugOuterClass.Tour getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_debug_GetDebugDataRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_debug_GetDebugDataRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_debug_GetDebugDataReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_debug_GetDebugDataReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_debug_Tour_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_debug_Tour_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013debug.proto\022\005debug\"*\n\023GetDebugDataRequ" +
      "est\022\023\n\013guardroomId\030\001 \001(\t\"/\n\021GetDebugData" +
      "Reply\022\032\n\005items\030\001 \003(\0132\013.debug.Tour\"k\n\004Tou" +
      "r\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\022\n\ncourseTyp" +
      "e\030\003 \001(\t\022\020\n\010duration\030\004 \001(\t\022\021\n\tstripName\030\005" +
      " \001(\t\022\020\n\010isActive\030\006 \001(\0102O\n\005Debug\022F\n\014GetDe" +
      "bugData\022\032.debug.GetDebugDataRequest\032\030.de" +
      "bug.GetDebugDataReply\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_debug_GetDebugDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_debug_GetDebugDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_debug_GetDebugDataRequest_descriptor,
        new java.lang.String[] { "GuardroomId", });
    internal_static_debug_GetDebugDataReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_debug_GetDebugDataReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_debug_GetDebugDataReply_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_debug_Tour_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_debug_Tour_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_debug_Tour_descriptor,
        new java.lang.String[] { "Id", "Name", "CourseType", "Duration", "StripName", "IsActive", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
